### ISSUE TITLE
What can open source projects do to be more inclusive of women and minorities?

### ISSUE THREAD

**Issue by SBoudrias** [partydelgado/ama#10]

**Comment by partydelgado** [comment]
This is a great question! If your aim is to get more women and minorities contributing to an open source project, I'd start with checking out meetups. In NYC, there are a ton of meetups for developers, and some directed toward particular minorities and women. It's really empowering when you're reaching out to a community to step into a group of like-minded, supportive people.

So my suggestion would be to sell your open source project to that meetup! [Women Who Code](http://www.meetup.com/WomenWhoCodeNYC/) is an excellent meetup that hosts coding workshops and speaker series. I've given talks with them before. You could message the organizer of the meetup and ask them to send a message to their subscribers, or get 5 min before the next meetup to pitch your open source project to the group. You could also attend one of the workshops and ask some developers if they want to take a look at your project!

In all, meetups are a great way to build your community. Once you start networking with a few people, it'll open the doors to many others.
