### ISSUE TITLE
How offensive do you find this tweet (Scale 1-10)??

### ISSUE THREAD

**Issue by jfox14** [partydelgado/ama#3]
https://twitter.com/thebitfactory/status/583715700302356480

Courtesy of a local Ohio Business accelerator.

**Comment by partydelgado** [comment]
TBH the tweet standing alone didn't give me enough information about what the person was trying to say, so I read the thread of 7 tweets. It's very offensive and so disappointingly ignorant. Really the worst part is that the person who wrote those tweets is trying to be open minded, but just so utterly missing the point. It's depressing, and shows that we need to do more educating in the community. We need to stop framing all stories around "the problem" or "conflict" with women in technology, and instead highlight successful and interesting women in engineering the same way we highlight men. Not to say we should stop admitting there is a gender gap, but show more than just one side of the conversation.
