### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [partydelgado/ama#4]
Screenshot please. I ask everyone this as it can tell a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by lambtron** [comment]
:hamburger:

**Comment by partydelgado** [comment]
![image1](https://cloud.githubusercontent.com/assets/1739388/8653982/af7654e8-2987-11e5-9184-13bd1231b29d.PNG)

My homescreen is all business. The next screen has more apps in folders, and a final screen for random/WIP apps.
