### ISSUE TITLE
If you were lucky enough to win the lottery, what would you do with the money?

### ISSUE THREAD

**Issue by sindresorhus** [partydelgado/ama#7]

**Comment by partydelgado** [comment]
Well, first I'd do some minor stuff like pay of my student loans (yay :/ ) and help out my family with their debts. Then I'd buy some property, and invest some of the money. Honestly that sort of thing seems so unreal to me that I can only think of mundane things like paying my bills and rent, haha. I've never had a lot of money, I'm not sure I'd know how to spend it. But if it was enough, and I started making good investments, I'd like to set up scholarships for low-income kids and help people get free access to the internet.
